# Generated by Django 6.0.3 on 2026-03-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.CharField(choices=[('Local', 'Local'), ('Global', 'Global')], default='Local', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived')], default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly fee for subscription projects', max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Subscription', 'Subscription')], default='Fixed', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pipeline', 'Pipeline'), ('Completed', 'Completed')], default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='timeline',
            field=models.CharField(default='Monthly Cycle', max_length=100),
        ),
    ]
