# Generated by Django 6.0.3 on 2026-03-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_client_region_client_status_project_monthly_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
