# Generated by Django 6.0.3 on 2026-03-09 11:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='rate_to_pkr',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Exchange rate to PKR', max_digits=18),
        ),
    ]
