# Generated by Django 6.0.3 on 2026-03-09 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_currency_last_updated_currency_rate_to_pkr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(blank=True, help_text='Company Employee ID', max_length=50, null=True, unique=True)),
                ('designation', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Terminated', 'Terminated'), ('Resigned', 'Resigned')], default='Active', max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employees/profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.currency')),
            ],
        ),
    ]
