# Generated by Django 6.0.3 on 2026-03-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_project_monthly_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Pipeline / Prospect', 'Pipeline / Prospect'), ('Active / In Progress', 'Active / In Progress'), ('On Hold', 'On Hold'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Active', max_length=50),
        ),
    ]
