# Generated by Django 6.0.3 on 2026-03-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_project_project_lead_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated tax percentage (e.g. SRB + Income Tax)', max_digits=5),
        ),
    ]
