# Generated by Django 6.0.3 on 2026-04-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_clientaccess_projectaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='can_view_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
