# Generated by Django 6.0.3 on 2026-04-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userpermission_can_view_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='can_view_all_data',
            field=models.BooleanField(default=False),
        ),
    ]
