# Generated by Django 6.0.3 on 2026-04-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_userpermission_can_view_all_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('name', 'account_type', 'currency')},
        ),
    ]
