# Generated by Django 6.0.3 on 2026-04-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_transactioncategory_alter_account_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/profiles/'),
        ),
    ]
