# Generated by Django 6.0.3 on 2026-04-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_userpermission_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tax_fixed_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed tax amount', max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='tax_type',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed', 'Fixed')], default='Percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated tax percentage', max_digits=5),
        ),
    ]
