# Generated by Django 6.0.3 on 2026-04-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_project_tax_fixed_amount_project_tax_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly fee for subscription projects', max_digits=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
