# Generated by Django 6.0.3 on 2026-04-23 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_project_monthly_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='commission_type',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed', 'Fixed')], default='Percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='commission_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='transaction',
            name='project_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_transactions', to='core.employee'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
