# Generated by Django 6.0.3 on 2026-04-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_transaction_commission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='charity_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
