# Generated by Django 6.0.3 on 2026-04-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_transaction_charity_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(default='Qonkar ERP', max_length=255)),
                ('software_logo', models.ImageField(blank=True, null=True, upload_to='system/branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='system/branding/')),
                ('footer_copyright', models.CharField(default='© 2024 Qonkar Finance. All rights reserved.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='charity_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
