# Generated by Django 6.0.3 on 2026-04-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_systemconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='accent_color',
            field=models.CharField(default='#10B981', help_text='Accent/Success color (Hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='brand_color',
            field=models.CharField(default='#0F172A', help_text='Primary theme color (Hex)', max_length=7),
        ),
    ]
