# Generated by Django 6.0.3 on 2026-05-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_project_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='can_manage_charity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='charity_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
