# Generated by Django 6.0.3 on 2026-05-05 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_userpermission_can_manage_charity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactioncategory',
            options={},
        ),
        migrations.CreateModel(
            name='ProjectPausePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pause_start', models.DateField(default=django.utils.timezone.now)),
                ('resume_date', models.DateField(blank=True, help_text='Leave blank if currently on hold', null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pause_periods', to='core.project')),
            ],
            options={
                'verbose_name_plural': 'Transaction Categories',
            },
        ),
        migrations.CreateModel(
            name='ProjectSubscriptionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_fee', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_fee', models.DecimalField(decimal_places=2, max_digits=15)),
                ('effective_date', models.DateField(default=django.utils.timezone.now, help_text='The date from which the new fee applies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_changes', to='core.project')),
            ],
            options={
                'ordering': ['effective_date'],
            },
        ),
    ]
