# Generated by Django 6.0.3 on 2026-05-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_transactioncategory_options_projectpauseperiod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='can_manage_subscriptions',
            field=models.BooleanField(default=False),
        ),
    ]
