# Generated by Django 6.0.3 on 2026-05-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('Auth', 'Authentication'), ('System', 'System Event'), ('Error', 'Error')], max_length=50),
        ),
    ]
