# Generated by Django 6.0.3 on 2026-03-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, help_text='Monthly fee for subscription projects', max_digits=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_budget',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
