# Generated by Django 6.0.3 on 2026-04-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_client_created_by_employee_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_billed_date',
            field=models.DateField(blank=True, help_text='The date of the last monthly invoice generated', null=True),
        ),
    ]
